import type { PopupStats } from '../../shared/types/stats';

export const MOCK_STATS: PopupStats = {
  activeTabs: 12,
  discardedTabs: 8,
  totalTabs: 20,
  totalDiscarded: 47,
  totalMemorySavedMB: 3760,
  currentlySleepingMB: 640,
  blockedDomainCount: 29,
  idleTimeoutMinutes: 15,
  isEnabled: true,
  trackerBlockingEnabled: true,
  webglEvictionEnabled: true,
  tabs: [
    {
      id: 1,
      title: 'Google Docs — Project Roadmap Q3 2025 Planning Document with Extended Title',
      url: 'https://docs.google.com/document/d/abc',
      favIconUrl: '',
      discarded: false,
      active: true,
      pinned: false,
      lastActive: Date.now(),
    },
    {
      id: 2,
      title: 'GitHub — MemPilot Repository',
      url: 'https://github.com/user/mempilot',
      favIconUrl: '',
      discarded: false,
      active: false,
      pinned: true,
      lastActive: Date.now() - 120000,
    },
    {
      id: 3,
      title: 'YouTube — Never Gonna Give You Up',
      url: 'https://youtube.com/watch?v=dQw4w9WgXcQ',
      favIconUrl: '',
      discarded: false,
      active: false,
      pinned: false,
      lastActive: Date.now() - 900000,
    },
    {
      id: 4,
      title: 'Stack Overflow — How to reduce Chrome memory usage',
      url: 'https://stackoverflow.com/questions/123',
      favIconUrl: '',
      discarded: true,
      active: false,
      pinned: false,
      lastActive: Date.now() - 3600000,
    },
    {
      id: 5,
      title: 'Twitter',
      url: 'https://twitter.com',
      favIconUrl: '',
      discarded: true,
      active: false,
      pinned: false,
      lastActive: Date.now() - 7200000,
    },
    {
      id: 6,
      title: 'Reddit — r/webdev',
      url: 'https://reddit.com/r/webdev',
      favIconUrl: '',
      discarded: false,
      active: false,
      pinned: false,
      lastActive: Date.now() - 300000,
    },
    {
      id: 7,
      title: 'Figma — MemPilot Design System',
      url: 'https://figma.com/file/abc',
      favIconUrl: '',
      discarded: true,
      active: false,
      pinned: false,
      lastActive: Date.now() - 5400000,
    },
    {
      id: 8,
      title: 'Linear — Sprint Board',
      url: 'https://linear.app/team/board',
      favIconUrl: '',
      discarded: false,
      active: false,
      pinned: false,
      lastActive: Date.now() - 600000,
    },
  ],
};
